### ISSUE TITLE
Stuck at Loading file

### ISSUE THREAD

**Issue by jayantanth** [yarl/vicuna#101]
![screenshot from 2017-01-27 02-29-52](https://cloud.githubusercontent.com/assets/1370149/22350103/948e657c-e438-11e6-82fe-c91738ce607b.png)

Using Ubuntu 16,adding  100MB+ pdf file abour 10 nos file.

**Comment by Silubr** [comment]
I can confirm that this happens with any file I’ve tried (even single, few kB ones) and with Oracle Java 9, Oracle Java 8 as well as OpenJDK 8. The last version of Vicuna to work on Ubuntu Xenial appears to be 1.20. Rgds

**Comment by Silubr** [comment]
Correction: current version also seems to work if built from git (should have tried that before). This might also work for @jayantanth

**Comment by distriker** [comment]
It happens to me in Debian 8.6 Jessie, with any file, single or not, small or heavy.

**Comment by FlominatorTM** [comment]
Does it work when you deactivate the option "load from subdirectories"? 

If yes, it might have the same origin as #97

**Comment by distriker** [comment]
Hi @FlominatorTM!
I had deactivated the option "load from subdirectories". I activated to test, and it happens again.

Regards

**Comment by marcpayne** [comment]
I also have this issue. When I start it from the command line, I see the following error:

```
Exception in thread "FFileLoading" java.lang.NullPointerException
	at cuploader.PFile.getName(PFile.java:1186)
	at com.sun.java.swing.plaf.gtk.GTKStyle.getInsets(GTKStyle.java:316)
	at javax.swing.plaf.synth.SynthStyle.installDefaults(SynthStyle.java:913)
	at javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(SynthLookAndFeel.java:265)
	at javax.swing.plaf.synth.SynthPanelUI.updateStyle(SynthPanelUI.java:117)
	at javax.swing.plaf.synth.SynthPanelUI.installDefaults(SynthPanelUI.java:100)
	at javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:56)
	at javax.swing.plaf.synth.SynthPanelUI.installUI(SynthPanelUI.java:62)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JPanel.setUI(JPanel.java:153)
	at javax.swing.JPanel.updateUI(JPanel.java:126)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:117)
	at cuploader.PFile.<init>(PFile.java:81)
	at cuploader.frames.FFileLoading$1.run(FFileLoading.java:140)
	at java.lang.Thread.run(Thread.java:748)
```

I selected a single OGG file to upload for testing purposes when this error occurred.

**Comment by FlominatorTM** [comment]
@marcpayne Does it work with JPEG files for you?

**Comment by marcpayne** [comment]
No, I get the same error and same behavior with JPEG files. I should also note that it works fine if I build from source.

**Comment by michal-josef-spacek** [comment]
@jayantanth @Silubr @ivanhercaz @FlominatorTM @marcpayne I am closing this ticket, there is no relevant information what happened. I fixed issue with loading of subdirectory. 
You could try 1.24-beta3 (https://github.com/yarl/vicuna/releases/tag/1.24-beta3) and check if is there some issue. If yes, you could reopen ticket and describe what happening.
