### ISSUE TITLE
Cannot add images if disabling "loading files from sub-folders"

### ISSUE THREAD

**Issue by mathieumd** [yarl/vicuna#105]
When I disable the option "loading files from sub-folders" (from the Program tab in Parameters settings), I cannot add files anymore. The error, only shown when Vicuna has been launched from console, is:

```
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
        at cuploader.frames.Main.addToArray(Main.java:1742)
        at cuploader.frames.Main.loadFiles(Main.java:939)
        at cuploader.frames.Main.access$400(Main.java:43)
        at cuploader.frames.Main$14.actionPerformed(Main.java:589)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
        at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802)
        at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
        at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
        at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
        at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
        at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
        at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
        at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
        at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
        at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
        at javax.swing.SwingUtilities.processKeyBindings(SwingUtilities.java:1587)
        at javax.swing.UIManager$2.postProcessKeyEvent(UIManager.java:1483)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:817)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
        at java.awt.Component.dispatchEventImpl(Component.java:4760)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Which seems to looks like #83, but I'm not very fluent in Java exceptions ;)

I'm running Vicuna 1.23 on Debian 9.0 Stretch with Java OpenJDK 8u121-b13-4.1. (OpenJDK 9 fails to start Vicuna as seen in #85).

**Comment by michal-josef-spacek** [comment]
Fix in #148
