### ISSUE TITLE
Exception in thread Server monitor

### ISSUE THREAD

**Issue by merkato** [yarl/vicuna#107]
lip 16, 2017 3:52:07 PM Wiki getCurrentDatabaseLag
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?maxlag=5&format=xml&action=query&meta=siteinfo&siprop=dbrepllag
Exception in thread "Server monitor (database lag)" java.lang.UnknownError: MW API error. Server response was: <?xml version="1.0"?><api servedby="mw1285"><error code="maxlag" info="Waiting for 10.64.0.87: 5.9668750762939 seconds lagged." host="10.64.0.87" lag="5.9668750762939" type="db" xml:space="preserve">See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &amp;lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&amp;gt; for notice of API deprecations and breaking changes.</error></api>

	at org.wikipedia.Wiki.fetch(Wiki.java:6049)
	at org.wikipedia.Wiki.getCurrentDatabaseLag(Wiki.java:979)
	at cuploader.ServerMonitor.run(ServerMonitor.java:36)
	at java.lang.Thread.run(Thread.java:748)

**Comment by saper** [comment]
Looks like the Commons server got lagged..
