### ISSUE TITLE
Crash - upable to login

### ISSUE THREAD

**Issue by osmvermesser** [yarl/vicuna#131]
hi !

till April 2021 serveral person had problems to login by correct password.

look:
https://commons.wikimedia.org/wiki/Commons_talk:Vicu%C3%B1aUploader#Server-Error
https://de.wikipedia.org/wiki/Wikipedia:Fragen_zur_Wikipedia#Vicu%C3%B1aUploader_....

regards Jan

**Comment by michal-josef-spacek** [comment]
@osmvermesser Hi, what version of vicuna has this issues?

**Comment by Speravir** [comment]
Michal, I am obviously not osmvermesser, but let me tell:  Using `java.exe` (so, Windows user here) instead of the default `javaw.exe` I get with Vicuna 1.23 and java …
``` 
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
```
… these error messages in the commandline (caution, some linebreaks inside of words):
```
Apr 03, 2021 2:07:02 AM Wiki namespace                                                                                  
INFORMATION: Fetching URL https://commons.wikimedia.org/w/api.php?maxlag=5&format=xml&action=query&meta=siteinfo&siprop=
namespaces                                                                                                              
Apr 03, 2021 2:07:06 AM Wiki namespace                                                                                  
INFORMATION: [commons.wikimedia.org] Successfully retrieved namespace list (41 namespaces)                              
Apr 03, 2021 2:07:06 AM Wiki getPageText                                                                                
INFORMATION: Fetching URL https://commons.wikimedia.org/w/index.php?maxlag=5&title=User%3AYarl%2FVicunaUploader%2Fversio
n&action=raw                                                                                                            
Apr 03, 2021 2:07:06 AM Wiki getPageText                                                                                
INFORMATION: [commons.wikimedia.org] Successfully retrieved text of User:Yarl/VicunaUploader/version                    
Exception in thread "FIntro: Splash screen/Updater" com.thoughtworks.xstream.converters.ConversionException: Cannot cons
truct cuploader.QuickTemplate as it does not have a no-args constructor : Cannot construct cuploader.QuickTemplate as it
 does not have a no-args constructor                                                                                    
---- Debugging information ----                                                                                         
message             : Cannot construct cuploader.QuickTemplate as it does not have a no-args constructor                
cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException                              
cause-message       : Cannot construct cuploader.QuickTemplate as it does not have a no-args constructor                
class               : cuploader.QuickTemplate                                                                           
required-type       : cuploader.QuickTemplate                                                                           
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter                                
path                : /settings/quickTemplates/template                                                                 
class[1]            : java.util.ArrayList                                                                               
converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter                               
class[2]            : cuploader.Settings                                                                                
version             : null                                                                                              
-------------------------------                                                                                         
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)                             
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)   
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)                      
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)                      
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConver
ter.java:71)                                                                                                            
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionC
onverter.java:79)                                                                                                       
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.ja
va:72)                                                                                                                  
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.ja
va:66)                                                                                                                  
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:61)   
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)                             
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)   
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)                      
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflection
Converter.java:355)                                                                                                     
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConv
erter.java:306)                                                                                                         
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConver
ter.java:234)                                                                                                           
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)                             
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)   
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)                      
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)                      
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)                              
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:
32)                                                                                                                     
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1058)                                                
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1042)                                                
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:913)                                                   
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:904)                                                   
        at cuploader.frames.Main.readSettings(Main.java:1153)                                                           
        at cuploader.frames.Main.<init>(Main.java:56)                                                                   
        at cuploader.frames.FIntro$1.run(FIntro.java:41)                                                                
        at java.lang.Thread.run(Thread.java:748)                                                                        
Caused by: com.thoughtworks.xstream.converters.reflection.ObjectAccessException: Cannot construct cuploader.QuickTemplat
e as it does not have a no-args constructor                                                                             
        at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.newInstance(PureJavaReflectionProvi
der.java:71)                                                                                                            
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.instantiateNewInstance(AbstractRef
lectionConverter.java:428)                                                                                              
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConver
ter.java:233)                                                                                                           
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)                             
        ... 28 more                                                                                                     
````
In regards to the last line there is no possibility to get this displayed, the output simply ended.

So, for me the program did not even start, and with javaw version I get only the start splash screen, but then nothing happens, and in task manager I can see that the execution is aborted.

I only just now noticed your user sub page in Wikimedia Commons [User:Skim/VicuñaUploader](https://commons.wikimedia.org/wiki/User:Skim/Vicu%C3%B1aUploader), but the link to the test version does not work for me (in Germany): I get an [error page](https://uloz.to/blocked) from uloz.to with
>Error 451!
>The page is blocked due to the decision of the authorities in your area.

which is rather unfortunate if I want to check whether the issue is still present with your test version.

**Comment by michal-josef-spacek** [comment]
@Speravir Last build is this: https://skim.cz/tmp/vicuna-1.24-ae5c63.zip
If you could try, will be great.

**Comment by Speravir** [comment]
> If you could try, will be great.

Program starts, but hangs at splash screen. Error message:
```
Exception in thread "FIntro: Splash screen/Updater" java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;)Ljava/util/List;                                                                                                          
        at cuploader.frames.FIntro.checkVersion(FIntro.java:212)                                                        
        at cuploader.frames.FIntro.access$100(FIntro.java:15)                                                           
        at cuploader.frames.FIntro$1.run(FIntro.java:39)                                                                
        at java.lang.Thread.run(Thread.java:748)
```

I would suggest to put the batch file into the root directory of Vicuna, not into the bin folder.

**Comment by michal-josef-spacek** [comment]
@Speravir This dist file is output of ./gradlew build in build/distributions directory. Default configuration of build distribution.

**Comment by michal-josef-spacek** [comment]
@Speravir Isn't this bug related to java version? (https://github.com/tukkek/javelin/issues/234)

I have:
`openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)`
and working.

**Comment by osmvermesser** [comment]
hi !

i use win10 and in my knowledge i start the bat-file in bin-folder.

then starts a never ending intro.

Log is: 
Exception in thread "FIntro: Splash screen/Updater" java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;)Ljava/util/List;
        at cuploader.frames.FIntro.checkVersion(FIntro.java:212)
        at cuploader.frames.FIntro.access$100(FIntro.java:15)
        at cuploader.frames.FIntro$1.run(FIntro.java:39)
        at java.lang.Thread.run(Unknown Source)

regards Jan

**Comment by osmvermesser** [comment]
> 
> 
> @osmvermesser Hi, what version of vicuna has this issues?

1.23

**Comment by osmvermesser** [comment]
current i install openjdk 16 and then it run.

the problem is, when the setting file exists an the next start the programm will not open.

after manuell delete the programm start - i should define new setting-parameters.

regards jan

**Comment by Speravir** [comment]
> @Speravir Isn't this bug related to java version? ([tukkek/javelin#234](https://github.com/tukkek/javelin/issues/234))
> 
> I have:
> 
> openjdk version "11.0.9.1" 2020-11-04

Aah, version 1.23 worked with Java 8 builds (maybe it was Oracle Java, I do not remember).

I now installed `openjdk version "11.0.10" 2021-01-19 LTS`, and the test build works! It should be mentioned that Java 8 is not supported anymore.

**Comment by michal-josef-spacek** [comment]
Between 1.23 and 1.24 i changed

**Comment by michal-josef-spacek** [comment]
The best way is use 1.24 version (old version of java are not supported). I could support bugfixes across this version. Still i need to know, what happened (version of os, version of java, version of vicuna, describe issue.) 

I am looking to #133 bug in last version actually.

**Comment by michal-josef-spacek** [comment]
I created new dev release: https://skim.cz/tmp/vicuna-1.24-a627f3.zip

**Comment by michal-josef-spacek** [comment]
@osmvermesser @Speravir Could you test this new version? If will be ok, I will release 1.24.

**Comment by osmvermesser** [comment]
hi!

i try current version:

Start and close - a settings.vicuna will be create - here the log:

```
F:\Programme\Wikipedia\OtherVersion\bin>vicuna.bat
Apr. 05, 2021 6:55:11 PM Wiki getSiteInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&siprop=namespaces%7Cnamespacealiases%7Cgeneral%7Cextensions&maxlag=5&meta=siteinfo&format=xml&action=query
Apr. 05, 2021 6:55:13 PM Wiki getSiteInfo
INFO: [commons.wikimedia.org] Successfully retrieved site info for commons.wikimedia.org
Apr. 05, 2021 6:55:13 PM Wiki getText
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=revisions&format=xml&action=query&rvprop=ids%7Ccontent
Apr. 05, 2021 6:55:13 PM Wiki getPageText
INFO: [commons.wikimedia.org] Successfully retrieved text of 1 pages.
Error: No converter available
---- Debugging information ----
message             : No converter available
type                : java.awt.Dimension
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field private static final long java.awt.Dimension.serialVersionUID accessible: module java.desktop does not "opens java.awt" to unnamed module @8dcc761
```

then i start programm again with existing settings.vicuna

`Apr. 05, 2021 6:55:11 PM Wiki getSiteInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&siprop=namespaces%7Cnamespacealiases%7Cgeneral%7Cextensions&maxlag=5&meta=siteinfo&format=xml&action=query
Apr. 05, 2021 6:55:13 PM Wiki getSiteInfo
INFO: [commons.wikimedia.org] Successfully retrieved site info for commons.wikimedia.org
Apr. 05, 2021 6:55:13 PM Wiki getText
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=revisions&format=xml&action=query&rvprop=ids%7Ccontent
Apr. 05, 2021 6:55:13 PM Wiki getPageText
INFO: [commons.wikimedia.org] Successfully retrieved text of 1 pages.
Error: No converter available
---- Debugging information ----
message             : No converter available
type                : java.awt.Dimension
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field private static final long java.awt.Dimension.serialVersionUID accessible: module java.desktop does not "opens java.awt" to unnamed module @8dcc761
-------------------------------
F:\Programme\Wikipedia\OtherVersion\bin>vicuna.bat
Apr. 05, 2021 6:56:53 PM Wiki getSiteInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&siprop=namespaces%7Cnamespacealiases%7Cgeneral%7Cextensions&maxlag=5&meta=siteinfo&format=xml&action=query
Apr. 05, 2021 6:56:54 PM Wiki getSiteInfo
INFO: [commons.wikimedia.org] Successfully retrieved site info for commons.wikimedia.org
Apr. 05, 2021 6:56:54 PM Wiki getText
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=revisions&format=xml&action=query&rvprop=ids%7Ccontent
Apr. 05, 2021 6:56:54 PM Wiki getPageText
INFO: [commons.wikimedia.org] Successfully retrieved text of 1 pages.
[Fatal Error] :54:1: XML document structures must start and end within the same entity.
Exception in thread "FIntro: Splash screen/Updater" com.thoughtworks.xstream.io.StreamException:
        at com.thoughtworks.xstream.io.xml.DomDriver.createReader(DomDriver.java:115)
        at com.thoughtworks.xstream.io.xml.DomDriver.createReader(DomDriver.java:80)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1273)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1264)
        at cuploader.frames.Main.readSettings(Main.java:1176)
        at cuploader.frames.Main.<init>(Main.java:61)
        at cuploader.frames.FIntro$1.run(FIntro.java:42)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: org.xml.sax.SAXParseException; lineNumber: 54; columnNumber: 1; XML document structures must start and end within the same entity.
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at com.thoughtworks.xstream.io.xml.DomDriver.createReader(DomDriver.java:108)
        ... 7 more
F:\Programme\Wikipedia\OtherVersion\bin>F:\Programme\Wikipedia\OtherVersion\bin>vicuna.bat
Der Befehl "F:\Programme\Wikipedia\OtherVersion\bin" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>Apr. 05, 2021 6:55:11 PM Wiki getSiteInfo
Der Befehl "Apr." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&siprop=namespaces%7Cnamespacealiases%7Cgeneral%7Cextensions&maxlag=5&meta=siteinfo&format=xml&action=query
Der Befehl "INFO:" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "siprop" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "maxlag" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "meta" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Ungültige Laufwerkangabe.
Der Befehl "action" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>Apr. 05, 2021 6:55:13 PM Wiki getSiteInfo
Der Befehl "Apr." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>INFO: [commons.wikimedia.org] Successfully retrieved site info for commons.wikimedia.org
Der Befehl "INFO:" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>Apr. 05, 2021 6:55:13 PM Wiki getText
Der Befehl "Apr." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=revisions&format=xml&action=query&rvprop=ids%7Ccontent
Der Befehl "INFO:" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "maxlag" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "prop" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Ungültige Laufwerkangabe.
Der Befehl "action" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "rvprop" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>Apr. 05, 2021 6:55:13 PM Wiki getPageText
Der Befehl "Apr." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>INFO: [commons.wikimedia.org] Successfully retrieved text of 1 pages.
Der Befehl "INFO:" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>Error: No converter available
Der Befehl "Error:" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>---- Debugging information ----
Der Befehl "----" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>message             : No converter available
Der Befehl "message" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>type                : java.awt.Dimension
Das System kann die angegebene Datei nicht finden.
Folgender Fehler trat auf: :.
Das System kann die angegebene Datei nicht finden.
Folgender Fehler trat auf: java.awt.Dimension.

F:\Programme\Wikipedia\OtherVersion\bin>converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
Der Befehl "converter" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

F:\Programme\Wikipedia\OtherVersion\bin>message[1]          : Unable to make field private static final long java.awt.Dimension.serialVersionUID accessible: module java.desktop does not "opens java.awt" to unnamed module @8dcc761

`

programm abort automatic.

then i manuell delete setting-file

current complete unable to start.

`Apr. 05, 2021 7:00:49 PM Wiki getSiteInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&siprop=namespaces%7Cnamespacealiases%7Cgeneral%7Cextensions&maxlag=5&meta=siteinfo&format=xml&action=query
Apr. 05, 2021 7:00:50 PM Wiki getSiteInfo
INFO: [commons.wikimedia.org] Successfully retrieved site info for commons.wikimedia.org
Apr. 05, 2021 7:00:50 PM Wiki getText
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=revisions&format=xml&action=query&rvprop=ids%7Ccontent
Apr. 05, 2021 7:00:50 PM Wiki getPageText
INFO: [commons.wikimedia.org] Successfully retrieved text of 1 pages.
[Fatal Error] :54:1: XML document structures must start and end within the same entity.
Exception in thread "FIntro: Splash screen/Updater" com.thoughtworks.xstream.io.StreamException:
        at com.thoughtworks.xstream.io.xml.DomDriver.createReader(DomDriver.java:115)
        at com.thoughtworks.xstream.io.xml.DomDriver.createReader(DomDriver.java:80)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1273)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1264)
        at cuploader.frames.Main.readSettings(Main.java:1176)
        at cuploader.frames.Main.<init>(Main.java:61)
        at cuploader.frames.FIntro$1.run(FIntro.java:42)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: org.xml.sax.SAXParseException; lineNumber: 54; columnNumber: 1; XML document structures must start and end within the same entity.
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at com.thoughtworks.xstream.io.xml.DomDriver.createReader(DomDriver.java:108)
        ... 7 more
F:\Programme\Wikipedia\OtherVersion\bin>`

Success: save session-file with right lat/lon
  <coor>
        <latitude>53.887623</latitude>
        <longitude>10.689654</longitude>
      </coor>

(close ticket #132)

regards Jan

PS: i installed openjdk16

**Comment by osmvermesser** [comment]
dont forget for release debug-messagebox to hide at the end.

jan

**Comment by Speravir** [comment]
> Could you test this new version?

First: I have nothing to upload in the moment. Could perhaps be worth asking in Commons:Village pump for more reviews.

On first start an error occurred. Unfortunately I did not safe it, but remembering osmvermesser’s info above about issues with the old settings file I disabled this. Then Vicuna started, but I got this warning:
```
Apr. 05, 2021 10:45:25 NACHM. Wiki getSiteInfo                                                                          
INFORMATION: Fetching URL https://commons.wikimedia.org/w/api.php?&siprop=namespaces%7Cnamespacealiases%7Cgeneral%7Cextensions&maxlag=5&meta=siteinfo&format=xml&action=query                                                                   
Apr. 05, 2021 10:45:26 NACHM. Wiki getSiteInfo                                                                          
INFORMATION: [commons.wikimedia.org] Successfully retrieved site info for commons.wikimedia.org                         
Apr. 05, 2021 10:45:26 NACHM. Wiki getText                                                                              
INFORMATION: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=revisions&format=xml&action=query&rvprop=ids%7Ccontent                                                                                                         
Apr. 05, 2021 10:45:27 NACHM. Wiki getPageText                                                                          
INFORMATION: [commons.wikimedia.org] Successfully retrieved text of 1 pages.                                            
Security framework of XStream not explicitly initialized, using predefined black list on your own risk.                 
WARNING: An illegal reflective access operation has occurred                                                            
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.reflection.FieldDictionary (file:/C:/Programs/Netzwerk/Mediawiki-Tools/Vicuna/lib/xstream-1.4.15.jar) to field java.awt.Dimension.serialVersionUID                    
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.converters.reflection.FieldDictionary                                                                                                                    
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations                   
WARNING: All illegal access operations will be denied in a future release
```
After this I disabled the new setting, and re-enabled the old one, but got now Vicuna started, and I the exact same messages, kind of strange.

**Comment by michal-josef-spacek** [comment]
@Speravir I created issue for your case (#136). This was present in 1.23 too and this is warning not error.

**Comment by michal-josef-spacek** [comment]
@osmvermesser This is crazy to read your issue. 

I believe, that you have broken settings.vicuna file on 54 line.
All lines after:
```
[Fatal Error] :54:1: XML document structures must start and end within the same entity.
```
describes error in XML file.

**Comment by michal-josef-spacek** [comment]
I created new dev release: https://skim.cz/tmp/vicuna-1.24-9607b3.zip
* newer xstream dist
* Remove info about default secure policy
* Remove warnings

**Comment by osmvermesser** [comment]
Hi !

today i could start and restart the programm.

i make a upload at 2021-04-06 ~19:00 but there was no gallery created on https://commons.wikimedia.org/wiki/User:JanTappenbeck/gallery - the profile is start by default profile. 

if i current open profile settings the option to create gallery is set.

regards Jan

**Comment by Speravir** [comment]
michal-josef-spacek :
> I created new dev release:

Osmvermesser:
> today i could start and restart the programm - successfull!.

Same here! :+1:
