### ISSUE TITLE
Vicuna doesn't save session on 1.24

### ISSUE THREAD

**Issue by michal-josef-spacek** [yarl/vicuna#133]
commit of vicuna: ae5c633ee25eb87d7dcf2c361cef0df160b42bfc
os: Debian
java:
```
woman:~> java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)
```

Error:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at cuploader.PFile.returnData(PFile.java:71)
        at cuploader.Data.getFilesForXML(Data.java:172)
        at cuploader.frames.Main.saveSessionFile(Main.java:1395)
        at cuploader.frames.Main.saveSession(Main.java:1374)
        at cuploader.frames.Main.mSaveSessionActionPerformed(Main.java:1121)
        at cuploader.frames.Main.access$1400(Main.java:48)
        at cuploader.frames.Main$16.actionPerformed(Main.java:634)
```

**Comment by michal-josef-spacek** [comment]
The issue is in situation when i am saving session with files without coordinates.

**Comment by michal-josef-spacek** [comment]
Issue has two parts:
1) Saving session without coordinates.
2) Loading session without coordinates.

**Comment by michal-josef-spacek** [comment]
Dev release with fix: https://skim.cz/tmp/vicuna-1.24-a627f3.zip
