### ISSUE TITLE
After restart (doing nothing before) I got "[Fatal Error] :54:1: XML document structures must start and end within the same entity."

### ISSUE THREAD

**Issue by vitaly-zdanevich** [yarl/vicuna#186]
Full error:

```
$ ./vicuna
Feb 15, 2024 1:55:43 PM Wiki getSiteInfo
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&siprop=namespaces%7Cnamespacealiases%7Cgeneral%7Cextensions&maxlag=5&meta=siteinfo&format=xml&action=query
Feb 15, 2024 1:55:44 PM Wiki getSiteInfo
INFO: [commons.wikimedia.org] Successfully retrieved site info for commons.wikimedia.org
Feb 15, 2024 1:55:44 PM Wiki getText
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?&maxlag=5&prop=revisions&format=xml&action=query&rvprop=ids%7Ccontent
Feb 15, 2024 1:55:44 PM Wiki getText
INFO: [commons.wikimedia.org] Successfully retrieved text of 1 pages.
[Fatal Error] :54:1: XML document structures must start and end within the same entity.
Exception in thread "FIntro: Splash screen/Updater" com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.DomDriver.createReader(DomDriver.java:115)
	at com.thoughtworks.xstream.io.xml.DomDriver.createReader(DomDriver.java:80)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1296)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1287)
	at cuploader.frames.Main.readSettings(Main.java:1189)
	at cuploader.frames.Main.<init>(Main.java:61)
	at cuploader.frames.FIntro$1.run(FIntro.java:43)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.xml.sax.SAXParseException; lineNumber: 54; columnNumber: 1; XML document structures must start and end within the same entity.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at com.thoughtworks.xstream.io.xml.DomDriver.createReader(DomDriver.java:108)
	... 7 more
```

**Comment by vitaly-zdanevich** [comment]
Hm, I found that `settings.vicuna` is corrupted:

```
$ cat settings.vicuna 
<settings>
  <server>commons.wikimedia.org</server>
  <username></username>
  <protocol>http</protocol>
  <path>/w</path>
  <author>own</author>
  <source></source>
  <permission></permission>
  <license>CC_BY_SA_3</license>
  <licenseCustom></licenseCustom>
  <attribution></attribution>
  <categories></categories>
  <extraText></extraText>
  <quickTemplates>
    <template>
      <name>Add English description</name>
      <template>{{en|1=%TEXT%}}</template>
      <active>true</active>
    </template>
    <template>
      <name>Add German description</name>
      <template>{{de|1=%TEXT%}}</template>
      <active>true</active>
    </template>
    <template>
      <name>Add French description</name>
      <template>{{fr|1=%TEXT%}}</template>
      <active>true</active>
    </template>
  </quickTemplates>
  <copyName>true</copyName>
  <copyDescription>true</copyDescription>
  <copyCategories>true</copyCategories>
  <showCatHints>true</showCatHints>
  <createGallery>true</createGallery>
  <galleryPage>gallery</galleryPage>
  <galleryHeader>0</galleryHeader>
  <galleryWidth>200</galleryWidth>
  <galleryOnTop>false</galleryOnTop>
  <readExifHour>false</readExifHour>
  <loadSubdirectory>false</loadSubdirectory>
  <renameAfterUpload>false</renameAfterUpload>
  <serverMonitorEnabled>true</serverMonitorEnabled>
  <askQuit>true</askQuit>
  <uploadSummary></uploadSummary>
  <fileDescSource>0</fileDescSource>
  <fileDescPath></fileDescPath>
  <defaultDir>/home/vitaly</defaultDir>
  <checkPrefixBlacklist>true</checkPrefixBlacklist>
  <checkIfExists>true</checkIfExists>
  <checkGPS>false</checkGPS>
  <checkUniqueNames>true</checkUniqueNames>
  <windowSize
```
