### ISSUE TITLE
NullPointerException after pasting a folder path in selection dialog and pressing OK

### ISSUE THREAD

**Issue by nicolas-raoul** [yarl/vicuna#78]
1. Launch VicuñaUploader 1.23 from Ubuntu 2015.10
2. Click "Read files"
3. Paste the local path to your files inside the "Selection" field
4. Click "OK"
5. A "Loading" dialog appears but never progresses. Screenshot and log:

![Vicuña](https://cloud.githubusercontent.com/assets/99590/15287656/5a766504-1b9f-11e6-81e2-8e8cb0a66226.png)

```
May 16, 2016 7:48:29 PM Wiki namespace
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?maxlag=5&format=xml&action=query&meta=siteinfo&siprop=namespaces
May 16, 2016 7:48:30 PM Wiki namespace
INFO: [commons.wikimedia.org] Successfully retrieved namespace list (39 namespaces)
May 16, 2016 7:48:30 PM Wiki getPageText
INFO: Fetching URL https://commons.wikimedia.org/w/index.php?maxlag=5&title=User%3AYarl%2FVicunaUploader%2Fversion&action=raw
May 16, 2016 7:48:30 PM Wiki getPageText
INFO: [commons.wikimedia.org] Successfully retrieved text of User:Yarl/VicunaUploader/version
Exception in thread "FFileLoading" java.lang.NullPointerException
        at cuploader.PFile.getName(PFile.java:1186)
        at com.sun.java.swing.plaf.gtk.GTKStyle.getInsets(GTKStyle.java:316)
        at javax.swing.plaf.synth.SynthStyle.installDefaults(SynthStyle.java:913)
        at javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(SynthLookAndFeel.java:265)
        at javax.swing.plaf.synth.SynthPanelUI.updateStyle(SynthPanelUI.java:117)
        at javax.swing.plaf.synth.SynthPanelUI.installDefaults(SynthPanelUI.java:100)
        at javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:56)
        at javax.swing.plaf.synth.SynthPanelUI.installUI(SynthPanelUI.java:62)
        at javax.swing.JComponent.setUI(JComponent.java:666)
        at javax.swing.JPanel.setUI(JPanel.java:153)
        at javax.swing.JPanel.updateUI(JPanel.java:126)
        at javax.swing.JPanel.<init>(JPanel.java:86)
        at javax.swing.JPanel.<init>(JPanel.java:109)
        at javax.swing.JPanel.<init>(JPanel.java:117)
        at cuploader.PFile.<init>(PFile.java:81)
        at cuploader.frames.FFileLoading$1.run(FFileLoading.java:140)
        at java.lang.Thread.run(Thread.java:745)
```

Workaround: Use Vicuña 1.20, the latest version that does not have this bug.
This bug affects Vicuña 1.21, 1.22, 1.23.

**Comment by nicolas-raoul** [comment]
I just built from latest Git (83e8772dc7ef7916349812b65f59a421cab7ecfa), and the problem is solved apparently, great, thanks :-)
