### ISSUE TITLE
Exception in Ubuntu when selecting or dragging files

### ISSUE THREAD

**Issue by nemobis** [yarl/vicuna#93]
Found in Ubuntu 14.04: when I click "read files" and select some files I want to upload, the dialog "Uploading: 1/X files" appears but never proceeds. In Ubuntu 15.10 the dialog just freezes at some point (might be the same as https://github.com/yarl/vicuna/issues/77 ). IN both cases there is an exception:

```
Exception in thread "FFileLoading" java.lang.NullPointerException
    at cuploader.PFile.getName(PFile.java:1186)
    at com.sun.java.swing.plaf.gtk.GTKStyle.getInsets(GTKStyle.java:315)
    at javax.swing.plaf.synth.SynthStyle.installDefaults(SynthStyle.java:913)
    at javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(SynthLookAndFeel.java:264)
    at javax.swing.plaf.synth.SynthPanelUI.updateStyle(SynthPanelUI.java:117)
    at javax.swing.plaf.synth.SynthPanelUI.installDefaults(SynthPanelUI.java:100)
    at javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:56)
    at javax.swing.plaf.synth.SynthPanelUI.installUI(SynthPanelUI.java:62)
    at javax.swing.JComponent.setUI(JComponent.java:656)
    at javax.swing.JPanel.setUI(JPanel.java:153)
    at javax.swing.JPanel.updateUI(JPanel.java:126)
    at javax.swing.JPanel.<init>(JPanel.java:86)
    at javax.swing.JPanel.<init>(JPanel.java:109)
    at javax.swing.JPanel.<init>(JPanel.java:117)
    at cuploader.PFile.<init>(PFile.java:81)
    at cuploader.frames.FFileLoading$1.run(FFileLoading.java:140)
    at java.lang.Thread.run(Thread.java:745)
^Cmarco@HP-Compaq-6730s:~/vicuna-1.23$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)
marco@HP-Compaq-6730s:~/vicuna-1.23$ uname -a
Linux HP-Compaq-6730s 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:32 UTC 2016 i686 i686 i686 GNU/Linux
```

Ubuntu 15.10:

```

$ java -jar vicuna.jar 
lug 27, 2016 11:48:04 AM Wiki namespace
INFORMAZIONI: Fetching URL https://commons.wikimedia.org/w/api.php?maxlag=5&format=xml&action=query&meta=siteinfo&siprop=namespaces
lug 27, 2016 11:48:05 AM Wiki namespace
INFORMAZIONI: [commons.wikimedia.org] Successfully retrieved namespace list (39 namespaces)
lug 27, 2016 11:48:05 AM Wiki getPageText
INFORMAZIONI: Fetching URL https://commons.wikimedia.org/w/index.php?maxlag=5&title=User%3AYarl%2FVicunaUploader%2Fversion&action=raw
lug 27, 2016 11:48:05 AM Wiki getPageText
INFORMAZIONI: [commons.wikimedia.org] Successfully retrieved text of User:Yarl/VicunaUploader/version
Exception in thread "FFileLoading" java.lang.NullPointerException
    at cuploader.PFile.getName(PFile.java:1186)
    at com.sun.java.swing.plaf.gtk.GTKStyle.getInsets(GTKStyle.java:315)
    at javax.swing.plaf.synth.SynthStyle.installDefaults(SynthStyle.java:913)
    at javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(SynthLookAndFeel.java:264)
    at javax.swing.plaf.synth.SynthPanelUI.updateStyle(SynthPanelUI.java:117)
    at javax.swing.plaf.synth.SynthPanelUI.installDefaults(SynthPanelUI.java:100)
    at javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:56)
    at javax.swing.plaf.synth.SynthPanelUI.installUI(SynthPanelUI.java:62)
    at javax.swing.JComponent.setUI(JComponent.java:656)
    at javax.swing.JPanel.setUI(JPanel.java:153)
    at javax.swing.JPanel.updateUI(JPanel.java:126)
    at javax.swing.JPanel.<init>(JPanel.java:86)
    at javax.swing.JPanel.<init>(JPanel.java:109)
    at javax.swing.JPanel.<init>(JPanel.java:117)
    at cuploader.PFile.<init>(PFile.java:81)
    at cuploader.frames.FFileLoading$1.run(FFileLoading.java:140)
    at java.lang.Thread.run(Thread.java:745)
$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.15.10.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

**Comment by ElGrafo** [comment]
I get a very similar looking error message on Linux Mint 17 when trying to load a file into Vicuna 1.23 (File → Read files). The "Loading" window/bar appears but then nothing happens.

```
$ java -jar ~/vicuna/vicuna.jar 
Jul 27, 2016 6:58:28 PM Wiki namespace
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?maxlag=5&format=xml&action=query&meta=siteinfo&siprop=namespaces
Jul 27, 2016 6:58:29 PM Wiki namespace
INFO: [commons.wikimedia.org] Successfully retrieved namespace list (39 namespaces)
Jul 27, 2016 6:58:29 PM Wiki getPageText
INFO: Fetching URL https://commons.wikimedia.org/w/index.php?maxlag=5&title=User%3AYarl%2FVicunaUploader%2Fversion&action=raw
Jul 27, 2016 6:58:30 PM Wiki getPageText
INFO: [commons.wikimedia.org] Successfully retrieved text of User:Yarl/VicunaUploader/version
Exception in thread "FFileLoading" java.lang.NullPointerException
	at cuploader.PFile.getName(PFile.java:1186)
	at com.sun.java.swing.plaf.gtk.GTKStyle.getInsets(GTKStyle.java:315)
	at javax.swing.plaf.synth.SynthStyle.installDefaults(SynthStyle.java:913)
	at javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(SynthLookAndFeel.java:264)
	at javax.swing.plaf.synth.SynthPanelUI.updateStyle(SynthPanelUI.java:117)
	at javax.swing.plaf.synth.SynthPanelUI.installDefaults(SynthPanelUI.java:100)
	at javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:56)
	at javax.swing.plaf.synth.SynthPanelUI.installUI(SynthPanelUI.java:62)
	at javax.swing.JComponent.setUI(JComponent.java:656)
	at javax.swing.JPanel.setUI(JPanel.java:153)
	at javax.swing.JPanel.updateUI(JPanel.java:126)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:117)
	at cuploader.PFile.<init>(PFile.java:81)
	at cuploader.frames.FFileLoading$1.run(FFileLoading.java:140)
	at java.lang.Thread.run(Thread.java:745)

$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

$ uname -a
Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by freddy2001** [comment]
Running as root `sudo java -jar vicuna.jar` has worked for me on Ubuntu 16.04 LTS

**Comment by saper** [comment]
Unreleased git master code will not crash like this; but additional protection has been added in https://github.com/yarl/vicuna/pull/94

**Comment by Aschroet** [comment]
Still having this issue. But i am glad that the workaround with sudo works. However, this is not optimal.

**Comment by michal-josef-spacek** [comment]
@Aschroet Could you describe this issue more precisely? I see that is issue with tName = null, but i don't see user use case.

FYI: Best way is test on https://github.com/yarl/vicuna/releases/tag/1.24-beta3

**Comment by ElGrafo** [comment]
FWIW, the problem does not seem to appear any more with 1.24-beta3 on Ubuntu 20.04.

**Comment by michal-josef-spacek** [comment]
FYI: https://github.com/yarl/vicuna/releases/tag/1.24-beta4

**Comment by michal-josef-spacek** [comment]
I am closing this ticket. When someone touch this issue again, please reopen or create new issue.
